version: '3.9'
services:
  pos:
    image: pos:0.1
    ports:
      - 8000:8000
    environment:
      - SENDGRID_API_KEY=SG.YOURAPIKEY
      - PORT= 8000
      - MONGO_USER =  monogo
      - MONGO_PASSWORD = mongo
      - SECRET = secret
      - EXPIRESIN = 30d
      - ACTIVESECRET = scret
      - ACTIVEXPIRES = 15m
      - RESETSECRET = secret
      - RESETEXPIRES = 15m
      - DBURL = mongodb+srv://mongo:password@cluster0.rkzoltz.mongodb.net/?retryWrites=true&w=majority  
    volumes:
      - public:/app/public
volumes:
  public:
    driver: local