env:
  CRYPTROUNDS: ${{ secrets.CRYPTROUNDS }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  JWTEXPIREIN: ${{ secrets.JWTEXPIREIN}}
  JWTSECRET: ${{ secrets.JWTSECRET}}
  NODE_ENV: ${{ secrets.NODE_ENV}}
  AZURESTORAGEACCOUNTKEY: ${{secrets.AZURESTORAGEACCOUNTKEY}}
  AZURECONTAINERNAME: ${{secrets.AZURECONTAINERNAME}}
  AZURESTROAGEACCOUNTNAME: ${{secrets.AZURESTROAGEACCOUNTNAME}}
  DIRECT_URL: ${{secrets.DIRECT_URL}}
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}}
  CLOUDINARY_URL: ${{secrets.CLOUDINARY_URL}}
  NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
  NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}

permissions:
  contents: write

on:
  push:
    branches: [main]

jobs:
  createDemo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: checkout demo branch
        run: |
          git checkout main
          git fetch origin
          git checkout demo
          git pull
          git merge origin/main
          git push origin demo

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "18.*"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Run Prisma Migration
        run: pnpm prisma migrate reset
