env:
  CRYPTROUNDS: ${{ secrets.CRYPTROUNDS }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  JWTEXPIREIN: ${{ secrets.JWTEXPIREIN}}
  JWTSECRET: ${{ secrets.JWTSECRET}}
  NODE_ENV: ${{ secrets.NODE_ENV}}
  AZURESTORAGEACCOUNTKEY: ${{secrets.AZURESTORAGEACCOUNTKEY}}
  AZURECONTAINERNAME: ${{secrets.AZURECONTAINERNAME}}
  AZURESTROAGEACCOUNTNAME: ${{secrets.AZURESTROAGEACCOUNTNAME}}
  DIRECT_URL: ${{secrets.DIRECT_URL}}
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}}
  CLOUDINARY_URL: ${{secrets.CLOUDINARY_URL}}
  NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
  NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}

on:
  push:
  pull_request:
    branches: [main]
jobs:
  valid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: "18.*"
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: check types
        run: pnpm run typecheck
      - name: linter
        run: pnpm run lint
